import { Offer } from './types/offer';

export const offers: Offer[] = [
  {
    city: {
      name: 'Hamburg',
      location: { latitude: 53.550341, longitude: 10.000654, zoom: 13 },
    },
    previewImage: 'https://8.react.pages.academy/static/hotel/6.jpg',
    images: [
      'https://8.react.pages.academy/static/hotel/8.jpg',
      'https://8.react.pages.academy/static/hotel/20.jpg',
      'https://8.react.pages.academy/static/hotel/11.jpg',
      'https://8.react.pages.academy/static/hotel/15.jpg',
      'https://8.react.pages.academy/static/hotel/10.jpg',
      'https://8.react.pages.academy/static/hotel/12.jpg',
      'https://8.react.pages.academy/static/hotel/1.jpg',
      'https://8.react.pages.academy/static/hotel/19.jpg',
      'https://8.react.pages.academy/static/hotel/14.jpg',
      'https://8.react.pages.academy/static/hotel/13.jpg',
      'https://8.react.pages.academy/static/hotel/7.jpg',
      'https://8.react.pages.academy/static/hotel/6.jpg',
      'https://8.react.pages.academy/static/hotel/18.jpg',
      'https://8.react.pages.academy/static/hotel/16.jpg',
    ],
    title: 'Amazing and Extremely Central Flat',
    isFavorite: false,
    isPremium: false,
    rating: 4.7,
    type: 'apartment',
    bedrooms: 1,
    maxAdults: 9,
    price: 462,
    goods: [
      'Laptop friendly workspace',
      'Baby seat',
      'Air conditioning',
      'Washer',
      'Breakfast',
    ],
    host: {
      id: 25,
      name: 'Angelina',
      isPro: true,
      avatarUrl: 'img/avatar-angelina.jpg',
    },
    description:
      'A new spacious villa, ne floor. All commodities, jacuzzi and beautiful scenery. Ideal for families or friends.',
    location: { latitude: 53.534341000000005, longitude: 9.998654, zoom: 16 },
    id: 1,
  },
  {
    city: {
      name: 'Hamburg',
      location: { latitude: 53.550341, longitude: 10.000654, zoom: 13 },
    },
    previewImage: 'https://8.react.pages.academy/static/hotel/4.jpg',
    images: [
      'https://8.react.pages.academy/static/hotel/13.jpg',
      'https://8.react.pages.academy/static/hotel/6.jpg',
      'https://8.react.pages.academy/static/hotel/18.jpg',
      'https://8.react.pages.academy/static/hotel/8.jpg',
      'https://8.react.pages.academy/static/hotel/12.jpg',
      'https://8.react.pages.academy/static/hotel/4.jpg',
      'https://8.react.pages.academy/static/hotel/11.jpg',
      'https://8.react.pages.academy/static/hotel/5.jpg',
      'https://8.react.pages.academy/static/hotel/7.jpg',
      'https://8.react.pages.academy/static/hotel/19.jpg',
      'https://8.react.pages.academy/static/hotel/20.jpg',
      'https://8.react.pages.academy/static/hotel/9.jpg',
      'https://8.react.pages.academy/static/hotel/15.jpg',
      'https://8.react.pages.academy/static/hotel/1.jpg',
    ],
    title: 'Wood and stone place',
    isFavorite: false,
    isPremium: false,
    rating: 4.9,
    type: 'room',
    bedrooms: 1,
    maxAdults: 2,
    price: 180,
    goods: ['Breakfast', 'Washer', 'Laptop friendly workspace'],
    host: {
      id: 25,
      name: 'Angelina',
      isPro: true,
      avatarUrl: 'img/avatar-angelina.jpg',
    },
    description:
      'A new spacious villa, one floor. All commodities, jacuzzi and beautiful scenery. Ideal for families or friends.',
    location: { latitude: 53.563341, longitude: 9.975654, zoom: 16 },
    id: 2,
  },
  {
    city: {
      name: 'Hamburg',
      location: { latitude: 53.550341, longitude: 10.000654, zoom: 13 },
    },
    previewImage: 'https://8.react.pages.academy/static/hotel/7.jpg',
    images: [
      'https://8.react.pages.academy/static/hotel/15.jpg',
      'https://8.react.pages.academy/static/hotel/19.jpg',
      'https://8.react.pages.academy/static/hotel/18.jpg',
      'https://8.react.pages.academy/static/hotel/10.jpg',
      'https://8.react.pages.academy/static/hotel/4.jpg',
      'https://8.react.pages.academy/static/hotel/17.jpg',
      'https://8.react.pages.academy/static/hotel/14.jpg',
      'https://8.react.pages.academy/static/hotel/11.jpg',
      'https://8.react.pages.academy/static/hotel/6.jpg',
      'https://8.react.pages.academy/static/hotel/1.jpg',
      'https://8.react.pages.academy/static/hotel/3.jpg',
      'https://8.react.pages.academy/static/hotel/20.jpg',
      'https://8.react.pages.academy/static/hotel/12.jpg',
      'https://8.react.pages.academy/static/hotel/8.jpg',
    ],
    title: 'Amazing and Extremely Central Flat',
    isFavorite: false,
    isPremium: false,
    rating: 4.7,
    type: 'hotel',
    bedrooms: 2,
    maxAdults: 5,
    price: 134,
    goods: [
      'Breakfast',
      'Washer',
      'Laptop friendly workspace',
      'Air conditioning',
    ],
    host: {
      id: 25,
      name: 'Angelina',
      isPro: true,
      avatarUrl: 'img/avatar-angelina.jpg',
    },
    description:
      'This is a place for dreamers to reset, reflect, and create. Designed with a \'slow\' pace in mind, our hope is that you enjoy every part of your stay; from making local coffee by drip in the morning, choosing the perfect record to put on as the sun sets.',
    location: {
      latitude: 53.540341000000005,
      longitude: 10.025654000000001,
      zoom: 16,
    },
    id: 3,
  },
  {
    city: {
      name: 'Amsterdam',
      location: { latitude: 52.37454, longitude: 4.897976, zoom: 13 },
    },
    previewImage: 'https://8.react.pages.academy/static/hotel/2.jpg',
    images: [
      'https://8.react.pages.academy/static/hotel/16.jpg',
      'https://8.react.pages.academy/static/hotel/20.jpg',
      'https://8.react.pages.academy/static/hotel/10.jpg',
      'https://8.react.pages.academy/static/hotel/12.jpg',
      'https://8.react.pages.academy/static/hotel/17.jpg',
      'https://8.react.pages.academy/static/hotel/7.jpg',
      'https://8.react.pages.academy/static/hotel/18.jpg',
      'https://8.react.pages.academy/static/hotel/5.jpg',
      'https://8.react.pages.academy/static/hotel/15.jpg',
      'https://8.react.pages.academy/static/hotel/1.jpg',
      'https://8.react.pages.academy/static/hotel/19.jpg',
      'https://8.react.pages.academy/static/hotel/6.jpg',
      'https://8.react.pages.academy/static/hotel/14.jpg',
      'https://8.react.pages.academy/static/hotel/9.jpg',
    ],
    title: 'Penthouse, 4-5 rooms + 5 balconies',
    isFavorite: false,
    isPremium: false,
    rating: 3.1,
    type: 'house',
    bedrooms: 3,
    maxAdults: 6,
    price: 822,
    goods: ['Laptop friendly workspace', 'Breakfast'],
    host: {
      id: 25,
      name: 'Angelina',
      isPro: true,
      avatarUrl: 'img/avatar-angelina.jpg',
    },
    description:
      'Discover daily local life in city center, friendly neighborhood, clandestine casino, karaoke, old-style artisans, art gallery and artist studio downstairs.',
    location: { latitude: 52.367540000000005, longitude: 4.883976, zoom: 16 },
    id: 4,
  },
  {
    city: {
      name: 'Cologne',
      location: { latitude: 50.938361, longitude: 6.959974, zoom: 13 },
    },
    previewImage: 'https://8.react.pages.academy/static/hotel/9.jpg',
    images: [
      'https://8.react.pages.academy/static/hotel/6.jpg',
      'https://8.react.pages.academy/static/hotel/17.jpg',
      'https://8.react.pages.academy/static/hotel/5.jpg',
      'https://8.react.pages.academy/static/hotel/14.jpg',
      'https://8.react.pages.academy/static/hotel/12.jpg',
      'https://8.react.pages.academy/static/hotel/4.jpg',
      'https://8.react.pages.academy/static/hotel/16.jpg',
      'https://8.react.pages.academy/static/hotel/11.jpg',
      'https://8.react.pages.academy/static/hotel/7.jpg',
      'https://8.react.pages.academy/static/hotel/18.jpg',
      'https://8.react.pages.academy/static/hotel/2.jpg',
      'https://8.react.pages.academy/static/hotel/20.jpg',
      'https://8.react.pages.academy/static/hotel/1.jpg',
      'https://8.react.pages.academy/static/hotel/10.jpg',
    ],
    title: 'Loft Studio in the Central Area',
    isFavorite: false,
    isPremium: true,
    rating: 3,
    type: 'apartment',
    bedrooms: 3,
    maxAdults: 9,
    price: 104,
    goods: [
      'Laptop friendly workspace',
      'Air conditioning',
      'Baby seat',
      'Washer',
      'Breakfast',
    ],
    host: {
      id: 25,
      name: 'Angelina',
      isPro: true,
      avatarUrl: 'img/avatar-angelina.jpg',
    },
    description:
      'Relax, rejuvenate and unplug in this ultimate rustic getaway experience in the country. In our beautiful screened Pondhouse, you can gaze at the stars and listen to the sounds of nature from your cozy warm bed.',
    location: { latitude: 50.959361, longitude: 6.978974, zoom: 16 },
    id: 5,
  },
  {
    city: {
      name: 'Dusseldorf',
      location: { latitude: 51.225402, longitude: 6.776314, zoom: 13 },
    },
    previewImage: 'https://8.react.pages.academy/static/hotel/4.jpg',
    images: [
      'https://8.react.pages.academy/static/hotel/18.jpg',
      'https://8.react.pages.academy/static/hotel/4.jpg',
      'https://8.react.pages.academy/static/hotel/10.jpg',
      'https://8.react.pages.academy/static/hotel/15.jpg',
      'https://8.react.pages.academy/static/hotel/6.jpg',
      'https://8.react.pages.academy/static/hotel/11.jpg',
      'https://8.react.pages.academy/static/hotel/2.jpg',
      'https://8.react.pages.academy/static/hotel/14.jpg',
      'https://8.react.pages.academy/static/hotel/17.jpg',
      'https://8.react.pages.academy/static/hotel/20.jpg',
      'https://8.react.pages.academy/static/hotel/13.jpg',
      'https://8.react.pages.academy/static/hotel/7.jpg',
      'https://8.react.pages.academy/static/hotel/12.jpg',
      'https://8.react.pages.academy/static/hotel/3.jpg',
    ],
    title: 'Perfectly located Castro',
    isFavorite: false,
    isPremium: false,
    rating: 3.5,
    type: 'room',
    bedrooms: 1,
    maxAdults: 2,
    price: 246,
    goods: [
      'Washer',
      'Air conditioning',
      'Laptop friendly workspace',
      'Breakfast',
    ],
    host: {
      id: 25,
      name: 'Angelina',
      isPro: true,
      avatarUrl: 'img/avatar-angelina.jpg',
    },
    description:
      'This is a place for dreamers to reset, reflect, and create. Designed with a \'slow\' pace in mind, our hope is that you enjoy every part of your stay; from making local coffee by drip in the morning, choosing the perfect record to put on as the sun sets.',
    location: { latitude: 51.250402, longitude: 6.7853140000000005, zoom: 16 },
    id: 6,
  },
  {
    city: {
      name: 'Cologne',
      location: { latitude: 50.938361, longitude: 6.959974, zoom: 13 },
    },
    previewImage: 'https://8.react.pages.academy/static/hotel/5.jpg',
    images: [
      'https://8.react.pages.academy/static/hotel/5.jpg',
      'https://8.react.pages.academy/static/hotel/10.jpg',
      'https://8.react.pages.academy/static/hotel/1.jpg',
      'https://8.react.pages.academy/static/hotel/14.jpg',
      'https://8.react.pages.academy/static/hotel/15.jpg',
      'https://8.react.pages.academy/static/hotel/19.jpg',
      'https://8.react.pages.academy/static/hotel/7.jpg',
      'https://8.react.pages.academy/static/hotel/3.jpg',
      'https://8.react.pages.academy/static/hotel/4.jpg',
      'https://8.react.pages.academy/static/hotel/17.jpg',
      'https://8.react.pages.academy/static/hotel/12.jpg',
      'https://8.react.pages.academy/static/hotel/11.jpg',
      'https://8.react.pages.academy/static/hotel/6.jpg',
      'https://8.react.pages.academy/static/hotel/2.jpg',
    ],
    title: 'The Joshua Tree House',
    isFavorite: false,
    isPremium: false,
    rating: 3.4,
    type: 'room',
    bedrooms: 1,
    maxAdults: 3,
    price: 181,
    goods: [
      'Towels',
      'Breakfast',
      'Laptop friendly workspace',
      'Washer',
      'Fridge',
      'Baby seat',
      'Air conditioning',
    ],
    host: {
      id: 25,
      name: 'Angelina',
      isPro: true,
      avatarUrl: 'img/avatar-angelina.jpg',
    },
    description:
      'A new spacious villa, one floor. All commodities, jacuzzi and beautiful scenery. Ideal for families or friends.',
    location: { latitude: 50.918461, longitude: 6.969974, zoom: 16 },
    id: 7,
  },
  {
    city: {
      name: 'Paris',
      location: { latitude: 48.85661, longitude: 2.351499, zoom: 13 },
    },
    previewImage: 'https://8.react.pages.academy/static/hotel/12.jpg',
    images: [
      'https://8.react.pages.academy/static/hotel/14.jpg',
      'https://8.react.pages.academy/static/hotel/4.jpg',
      'https://8.react.pages.academy/static/hotel/18.jpg',
      'https://8.react.pages.academy/static/hotel/3.jpg',
      'https://8.react.pages.academy/static/hotel/13.jpg',
      'https://8.react.pages.academy/static/hotel/2.jpg',
      'https://8.react.pages.academy/static/hotel/20.jpg',
      'https://8.react.pages.academy/static/hotel/10.jpg',
      'https://8.react.pages.academy/static/hotel/11.jpg',
      'https://8.react.pages.academy/static/hotel/16.jpg',
      'https://8.react.pages.academy/static/hotel/6.jpg',
      'https://8.react.pages.academy/static/hotel/15.jpg',
      'https://8.react.pages.academy/static/hotel/9.jpg',
      'https://8.react.pages.academy/static/hotel/7.jpg',
    ],
    title: 'Amazing and Extremely Central Flat',
    isFavorite: false,
    isPremium: false,
    rating: 2,
    type: 'hotel',
    bedrooms: 2,
    maxAdults: 4,
    price: 441,
    goods: [
      'Laptop friendly workspace',
      'Towels',
      'Air conditioning',
      'Baby seat',
      'Breakfast',
      'Washer',
      'Fridge',
    ],
    host: {
      id: 25,
      name: 'Angelina',
      isPro: true,
      avatarUrl: 'img/avatar-angelina.jpg',
    },
    description:
      'Relax, rejuvenate and unplug in this ultimate rustic getaway experience in the country. In our beautiful screened Pondhouse, you can gaze at the stars and listen to the sounds of nature from your cozy warm bed.',
    location: { latitude: 48.83961, longitude: 2.342499, zoom: 16 },
    id: 8,
  },
  {
    city: {
      name: 'Amsterdam',
      location: { latitude: 52.37454, longitude: 4.897976, zoom: 13 },
    },
    previewImage: 'https://8.react.pages.academy/static/hotel/4.jpg',
    images: [
      'https://8.react.pages.academy/static/hotel/18.jpg',
      'https://8.react.pages.academy/static/hotel/15.jpg',
      'https://8.react.pages.academy/static/hotel/1.jpg',
      'https://8.react.pages.academy/static/hotel/17.jpg',
      'https://8.react.pages.academy/static/hotel/11.jpg',
      'https://8.react.pages.academy/static/hotel/19.jpg',
      'https://8.react.pages.academy/static/hotel/9.jpg',
      'https://8.react.pages.academy/static/hotel/14.jpg',
      'https://8.react.pages.academy/static/hotel/10.jpg',
      'https://8.react.pages.academy/static/hotel/20.jpg',
      'https://8.react.pages.academy/static/hotel/6.jpg',
      'https://8.react.pages.academy/static/hotel/13.jpg',
      'https://8.react.pages.academy/static/hotel/2.jpg',
      'https://8.react.pages.academy/static/hotel/5.jpg',
    ],
    title: 'Penthouse, 4-5 rooms + 5 balconies',
    isFavorite: false,
    isPremium: true,
    rating: 3,
    type: 'house',
    bedrooms: 1,
    maxAdults: 10,
    price: 683,
    goods: [
      'Dishwasher',
      'Baby seat',
      'Breakfast',
      'Air conditioning',
      'Fridge',
      'Laptop friendly workspace',
      'Washer',
      'Towels',
    ],
    host: {
      id: 25,
      name: 'Angelina',
      isPro: true,
      avatarUrl: 'img/avatar-angelina.jpg',
    },
    description:
      'I am happy to welcome you to my apartment in the city center! Three words: location, cosy and chic!',
    location: { latitude: 52.36554, longitude: 4.911976, zoom: 16 },
    id: 9,
  },
  {
    city: {
      name: 'Hamburg',
      location: { latitude: 53.550341, longitude: 10.000654, zoom: 13 },
    },
    previewImage: 'https://8.react.pages.academy/static/hotel/19.jpg',
    images: [
      'https://8.react.pages.academy/static/hotel/16.jpg',
      'https://8.react.pages.academy/static/hotel/11.jpg',
      'https://8.react.pages.academy/static/hotel/14.jpg',
      'https://8.react.pages.academy/static/hotel/17.jpg',
      'https://8.react.pages.academy/static/hotel/10.jpg',
      'https://8.react.pages.academy/static/hotel/9.jpg',
      'https://8.react.pages.academy/static/hotel/8.jpg',
      'https://8.react.pages.academy/static/hotel/3.jpg',
      'https://8.react.pages.academy/static/hotel/13.jpg',
      'https://8.react.pages.academy/static/hotel/15.jpg',
      'https://8.react.pages.academy/static/hotel/12.jpg',
      'https://8.react.pages.academy/static/hotel/7.jpg',
      'https://8.react.pages.academy/static/hotel/2.jpg',
      'https://8.react.pages.academy/static/hotel/1.jpg',
    ],
    title: 'Wood and stone place',
    isFavorite: false,
    isPremium: false,
    rating: 2.9,
    type: 'room',
    bedrooms: 1,
    maxAdults: 1,
    price: 153,
    goods: ['Washer', 'Breakfast', 'Laptop friendly workspace'],
    host: {
      id: 25,
      name: 'Angelina',
      isPro: true,
      avatarUrl: 'img/avatar-angelina.jpg',
    },
    description:
      'I rent out a very sunny and bright apartment only 7 minutes walking distance to the metro station. The apartment has a spacious living room with a kitchen, one bedroom and a bathroom with mit bath. A terrace can be used in summer.',
    location: { latitude: 53.565341000000004, longitude: 9.978654, zoom: 16 },
    id: 10,
  },
];
